#!/bin/sh

banner(){
echo -n "X19fX19fX19fX19fX18uX19fLiAgX19fX18gICAgX19fX19fXyAgICBfX19fX19fICAgClxfICAgX19fIFxfXyAgfCAgIHwgLyAgXyAgXCAgIFwgICAgICBcICAgXCAgICAgIFwgIAovICAgIFwgIFwvLyAgIHwgICB8LyAgL19cICBcICAvICAgfCAgIFwgIC8gICB8ICAgXCAKXCAgICAgXF9fX1xfX19fICAgLyAgICB8ICAgIFwvICAgIHwgICAgXC8gICAgfCAgICBcCiBcX19fX19fICAvIF9fX19fX1xfX19ffF9fICAvXF9fX198X18gIC9cX19fX3xfXyAgLwogICAgICAgIFwvXC8gICAgICAgICAgICAgIFwvICAgICAgICAgXC8gICAgICAgICBcLyAKICAgICAgICAgICAgUEUzMi9QRTMyKysgTmFub21pdGUgUGFja2VyCg==" | base64 -d
echo " "
}


TOOLSDIR=$(pwd)/tools
RESDIR=$(pwd)/res

if [ -z "$1" ]
then
	echo "[!] Please supply the path to the exec to patch"
	exit
fi
ARCH=$(file $1 | grep PE32+)
if [ -z "$ARCH" ]
then
	PREFIXMGW=i686
else
	PREFIXMGW=x86_64
fi
banner
echo "[.] Nanomiting the executable..."
$TOOLSDIR/mite.py $1 #>>/dev/null
echo "[+] Generated $1-mited and $1-table"
echo "[.] Compressing mited exec and nanomite table ..."
$TOOLSDIR/creatersrc $1-mited $RESDIR/x32.res
$TOOLSDIR/creatersrc $1-table $RESDIR/nm32.res
echo "[.] Making and linking everything ..."
make PREFIXCC=$PREFIXMGW
echo "[+] Executable nanomited and packed!"
rm $1-mited $1-table
make clean
