#ifndef API_FUNCTION_H
# define API_FUNCTION

typedef BOOL (WINAPI *CREATEPROCESSW)(LPCTSTR, LPWSTR, LPSECURITY_ATTRIBUTES, LPSECURITY_ATTRIBUTES, BOOL, DWORD, LPVOID, LPCSTR, LPSTARTUPINFO, LPPROCESS_INFORMATION);
typedef NTSTATUS (WINAPI *NTQUERYINFORMATIONPROCESS)(HANDLE, int, PVOID, ULONG, PULONG);
typedef BOOL (WINAPI *READPROCESSMEMORY)(HANDLE, LPCVOID, LPVOID, SIZE_T, SIZE_T*);
typedef NTSTATUS (WINAPI *UNMAPVIEWOFSECTION)(HANDLE, PVOID);
typedef LPVOID (WINAPI *VIRTUALALLOCEX)(HANDLE, LPVOID, SIZE_T, DWORD, DWORD);
typedef	NTSTATUS (WINAPI *DECOMPRESSBUFF)(USHORT, PUCHAR, ULONG, PUCHAR, ULONG, PULONG);
typedef HRSRC (WINAPI *FINDRESOURCE)(HANDLE, LPWSTR, LPCTSTR);
typedef HGLOBAL (WINAPI *LOADRESOURCE)(HMODULE, HRSRC);
typedef LPVOID	(WINAPI *LOCKRESOURCE)(HGLOBAL);
typedef BOOL (WINAPI *WRITEPROCESSMEM)(HANDLE, LPVOID, LPCVOID, SIZE_T, SIZE_T*);
typedef BOOL (WINAPI *GETTHREADCONTEXT)(HANDLE, LPCONTEXT);
typedef BOOL (WINAPI *SETTHREADCONTEXT)(HANDLE, LPCONTEXT);
typedef DWORD (WINAPI *RESUMETHREAD)(HANDLE);
typedef BOOL (WINAPI *DEBUGACTIVEPROC)(DWORD);
typedef BOOL (WINAPI *WAITFORDEBUGEVENT)(LPDEBUG_EVENT, DWORD);
typedef BOOL (WINAPI *CONTINUEDEBUGEVENT)(DWORD, DWORD, DWORD);
typedef BOOL (WINAPI *GETMODULEFILENAME)(HMODULE, LPWSTR, DWORD);

#endif
